"""Add job_role_id to UserProfile

Revision ID: 8a0517c20f85
Revises: 3d6586eb9355
Create Date: 2026-08-30 20:21:24.640057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a0517c20f85'
down_revision: Union[str, None] = '3d6586eb9355'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('job_role_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'user_profile', 'job_role', ['job_role_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profile', type_='foreignkey')
    op.drop_column('user_profile', 'job_role_id')
    # ### end Alembic commands ###
