"""add_ai_document_and_mcq_metadata

Revision ID: dd1bc932975d
Revises: 8a0517c20f85
Create Date: 2026-08-30 21:40:29.107800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd1bc932975d'
down_revision: Union[str, None] = '8a0517c20f85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('document', sa.Column('mime_type', sa.String(length=100), nullable=True))
    op.add_column('document', sa.Column('uploaded_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'document', 'app_user', ['uploaded_by'], ['id'], ondelete='SET NULL')
    op.add_column('question', sa.Column('generation_method', sa.String(length=50), nullable=True))
    op.add_column('question', sa.Column('ai_model', sa.String(length=100), nullable=True))
    op.add_column('question', sa.Column('grounding_score', sa.Float(), nullable=True))
    op.add_column('question', sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'metadata_json')
    op.drop_column('question', 'grounding_score')
    op.drop_column('question', 'ai_model')
    op.drop_column('question', 'generation_method')
    op.drop_constraint(None, 'document', type_='foreignkey')
    op.drop_column('document', 'uploaded_by')
    op.drop_column('document', 'mime_type')
    op.drop_column('document', 'status')
    # ### end Alembic commands ###
